# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: neko-net irc
#email: noreply@neko-net.org
description: > # this means to ignore newlines until "baseurl:"
  The neko-net IRC network's main homepage with news, servers and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.neko-net.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
